import "./globals.css";
import { Inter } from "next/font/google";
import { ProductsProvider } from "@/context/ProductsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QR Based Transactions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProductsProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ProductsProvider>
  );
}
